languageCode = "zh-cn"
languageName = "ç®€ä½“ä¸­æ–‡"
weight = 1
title = "å­¦é”‹ xuefeng"

[params]
  displayName = "ç®€ä½“ä¸­æ–‡"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/avatar_capy_logo.png"
  description = "ä¸€ä¸ªå¼ºå¤§ã€è½»é‡çº§çš„ Hugo ä¸»é¢˜ã€‚"

[params.author]
  name = "å­¦é”‹ xuefeng"
  image = "img/avatar_profile_capy.png"
  headline = "ç”¨äº§å“æ€ç»´è§£é” AIï¼Œç”¨ AI å†é€ äº§å“ã€‚æ¬¢è¿ä¸€èµ·å†²æµª ğŸš¤"
  bio = "ç”¨äº§å“æ€ç»´è§£é” AIï¼Œç”¨ AI å†é€ äº§å“ã€‚æ¬¢è¿ä¸€èµ·å†²æµª ğŸš¤"
  links = [
    { x-twitter = "https://x.com/ailen_xuefeng" },
    { github = "https://github.com/Alllen66" },
    { youtube = "https://www.youtube.com/@xuefeng_ai" },
    { bilibili = "https://space.bilibili.com/487999630" },
    { xiaohongshu = "https://www.xiaohongshu.com/user/profile/5791000e50c4b420d97809da" },
    { wechat = "/wechat/" },
    { gongzhonghao = "/gongzhonghao/" },
    { jike = "/jike/" },
  ]